# Generated by Django 5.2.17 on 2026-09-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='product_active_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='catalog_product_price_gt_zero'), models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='catalog_product_stock_gte_zero')],
            },
        ),
    ]
